name: Quick Deploy to Yandex Cloud

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Yandex Cloud CLI
      uses: yandex-cloud/yc-cli-action@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}
        
    - name: Deploy application
      run: |
        echo "🚀 Развертывание в ${{ github.event.inputs.environment }}..."
        
        # Получаем информацию о сервере
        INSTANCE_ID=$(yc compute instance list --format json | jq -r '.[0].id')
        EXTERNAL_IP=$(yc compute instance list --format json | jq -r '.[0].network_interfaces[0].primary_v4_address.one_to_one_nat.address')
        
        echo "📡 Подключение к серверу $EXTERNAL_IP..."
        
        # Создаем скрипт развертывания
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "🔄 Обновление кода из GitHub..."
        
        # Переходим в директорию проекта
        cd /home/ubuntu/domeo-doors/app || {
          echo "📁 Клонирование репозитория..."
          git clone https://github.com/$GITHUB_REPOSITORY.git domeo-doors
          cd domeo-doors/app
        }
        
        # Обновляем код
        git pull origin main
        
        # Устанавливаем зависимости
        echo "📦 Установка зависимостей..."
        npm ci --only=production
        
        # Генерируем Prisma клиент
        echo "🗄️ Генерация Prisma клиента..."
        npx prisma generate
        
        # Применяем миграции
        echo "🔄 Применение миграций..."
        npx prisma db push
        
        # Собираем приложение
        echo "🔨 Сборка приложения..."
        npm run build
        
        # Останавливаем старый процесс
        echo "⏹️ Остановка старого процесса..."
        pkill -f "npm start" || true
        sleep 2
        
        # Запускаем новое приложение
        echo "▶️ Запуск приложения..."
        nohup npm start > app.log 2>&1 &
        
        # Ждем запуска
        sleep 10
        
        # Проверяем статус
        if curl -f http://localhost:3000/api/health; then
          echo "✅ Приложение успешно запущено!"
        else
          echo "❌ Ошибка запуска приложения"
          cat app.log
          exit 1
        fi
        EOF
        
        # Передаем переменные окружения
        export GITHUB_REPOSITORY="${{ github.repository }}"
        
        # Выполняем развертывание
        yc compute instance execute $INSTANCE_ID --command "bash -s" < deploy.sh
        
        echo "🎉 Развертывание завершено!"
        echo "🌐 URL: http://$EXTERNAL_IP:3000"
        echo "📊 Админка: http://$EXTERNAL_IP:3000/admin"
