name: Smoke & Guards

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: app

jobs:
  guard-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run OpenAPI guard (monorepo path)
        run: |
          python scripts/spec_guard.py --spec openapi.yaml

  remote-smoke:
    runs-on: ubuntu-latest
    if: ${{ secrets.DEV_BASE_URL != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Remote smoke against DEV_BASE_URL
        env:
          BASE_URL: ${{ secrets.DEV_BASE_URL }}
        run: |
          bash scripts/smoke.sh

  prod-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Build Next.js
        run: npm run build
      - name: Start Next in background
        run: |
          nohup npm run start -- -p 3000 > .next-start.log 2>&1 &
      - name: Wait for server
        run: npx --yes wait-on http://127.0.0.1:3000/api/health
      - name: Run local smoke against started server
        env:
          BASE_URL: http://127.0.0.1:3000
        run: bash scripts/smoke.sh
      - name: Show server logs on failure
        if: failure()
        run: |
          echo "---- .next-start.log ----"
          sed -n '1,200p' .next-start.log || true
