version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: domeo
      POSTGRES_USER: domeo
      POSTGRES_PASSWORD: domeo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  db_data:
