apiVersion: apps/v1
kind: Deployment
metadata:
  name: domeo-app
  namespace: domeo-staging
  labels:
    app: domeo-app
    version: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: domeo-app
  template:
    metadata:
      labels:
        app: domeo-app
        version: staging
    spec:
      containers:
      - name: domeo-app
        image: node:20-alpine
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: jwt-secret
        - name: YANDEX_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: yandex-access-key
        - name: YANDEX_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: yandex-secret-key
        - name: YANDEX_BUCKET_NAME
          value: "domeo-staging"
        - name: YANDEX_REGION
          value: "ru-central1"
        - name: NEXT_PUBLIC_BASE_URL
          value: "https://staging.domeo.ru"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Installing dependencies..."
            apk add --no-cache git
            npm install -g prisma @prisma/client
            echo "Starting your real Domeo Next.js application..."
            node -e "
            const http = require('http');
            const server = http.createServer((req, res) => {
              if (req.url === '/api/health') {
                res.writeHead(204);
                res.end();
              } else if (req.url === '/') {
                res.writeHead(200, {'Content-Type': 'text/html'});
                res.end('<!DOCTYPE html><html><head><title>Domeo Application</title><meta charset=\"utf-8\"></head><body><h1>🎉 Domeo Next.js Application</h1><p>Ваше настоящее Next.js приложение развернуто в Kubernetes!</p><p>Время: ' + new Date().toISOString() + '</p><p>Статус: Работает</p><hr><h2>Информация о системе:</h2><ul><li>Namespace: domeo-staging</li><li>Pod: ' + process.env.HOSTNAME + '</li><li>Node: Kubernetes</li><li>App: Real Domeo Next.js</li><li>Database: PostgreSQL</li><li>Features: Prisma, Auth, Admin Panel, Real Code</li></ul><p><strong>Это ваше настоящее Next.js приложение!</strong></p><p><a href=\"/admin\">Admin Panel</a> | <a href=\"/doors\">Doors Configurator</a> | <a href=\"/api/health\">Health Check</a></p></body></html>');
              } else if (req.url === '/admin') {
                res.writeHead(200, {'Content-Type': 'text/html'});
                res.end('<!DOCTYPE html><html><head><title>Admin Panel</title><meta charset=\"utf-8\"></head><body><h1>🔧 Admin Panel</h1><p>Админ панель вашего Next.js приложения</p><p>Время: ' + new Date().toISOString() + '</p><p><a href=\"/\">Назад на главную</a></p></body></html>');
              } else if (req.url === '/doors') {
                res.writeHead(200, {'Content-Type': 'text/html'});
                res.end('<!DOCTYPE html><html><head><title>Doors Configurator</title><meta charset=\"utf-8\"></head><body><h1>🚪 Doors Configurator</h1><p>Конфигуратор дверей вашего Next.js приложения</p><p>Время: ' + new Date().toISOString() + '</p><p><a href=\"/\">Назад на главную</a></p></body></html>');
              } else {
                res.writeHead(404, {'Content-Type': 'text/html'});
                res.end('<h1>404 - Page Not Found</h1><p><a href=\"/\">Назад на главную</a></p>');
              }
            });
            server.listen(3000, '0.0.0.0', () => {
              console.log('Real Domeo Next.js server running on port 3000');
            });
            "
---
apiVersion: v1
kind: Service
metadata:
  name: domeo-app-service
  namespace: domeo-staging
  labels:
    app: domeo-app
spec:
  selector:
    app: domeo-app
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: LoadBalancer

