apiVersion: v1
kind: Namespace
metadata:
  name: domeo-staging
  labels:
    name: domeo-staging
    environment: staging
---
apiVersion: v1
kind: Secret
metadata:
  name: domeo-secrets
  namespace: domeo-staging
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2RvbWVvX2FkbWluOmpieC1SOEItUFNULWQ4eEBjOXE5bHRoaWdvMm5jZ20zb3JmZS5tZGIueWFuZGV4Y2xvdWQubmV0OjY0MzIvZG9tZW8=
  jwt-secret: c3RhZ2luZy1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  yandex-access-key: c3RhZ2luZy1hY2Nlc3Mta2V5
  yandex-secret-key: c3RhZ2luZy1zZWNyZXQta2V5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domeo-app
  namespace: domeo-staging
  labels:
    app: domeo-app
    version: staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: domeo-app
  template:
    metadata:
      labels:
        app: domeo-app
        version: staging
    spec:
      containers:
      - name: domeo-app
        image: cr.yandex/crpuein3jvjccnafs2vc/domeo-app:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: jwt-secret
        - name: YANDEX_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: yandex-access-key
        - name: YANDEX_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: yandex-secret-key
        - name: YANDEX_BUCKET_NAME
          value: "domeo-staging"
        - name: YANDEX_REGION
          value: "ru-central1"
        - name: NEXT_PUBLIC_BASE_URL
          value: "https://staging.domeo.ru"
        - name: PRISMA_SKIP_POSTINSTALL_GENERATE
          value: "true"
        - name: PRISMA_CLI_BINARY_TARGETS
          value: "linux-musl-openssl-3.0.x"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: domeo-app-service
  namespace: domeo-staging
  labels:
    app: domeo-app
spec:
  type: LoadBalancer
  selector:
    app: domeo-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domeo-ingress
  namespace: domeo-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: staging.domeo.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: domeo-app-service
            port:
              number: 80

