apiVersion: batch/v1
kind: Job
metadata:
  name: domeo-migrations
  namespace: domeo-staging
  labels:
    app: domeo-migrations
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: migrations
        image: node:20-alpine
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: domeo-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      restartPolicy: Never

