ALTER TABLE products ADD COLUMN IF NOT EXISTS sku_1c TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS collection TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier_item_name TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier_color_finish TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price_opt NUMERIC(12,2);
