name: CD
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ${{ secrets.VM_APP_DIR }}
            git fetch origin
            git checkout main
            git pull --ff-only
            bash scripts/verify_truths.sh
            python3 scripts/spec_guard.py || true
            bash scripts/deploy_vm.sh
            bash scripts/smoke.sh "http://localhost:3000"
